language: r
sudo: false
cache: packages

r:
  - release
  - devel

r_github_packages:
  - jimhester/covr

env:
  global:
    - secure: "e2QLomaUqNvpHnGNdBXS4VO2/UWokrKl9UgYrqWo+fhpXaJiJuONNPNL44BuWZR2Cy7noTHrevVbTKBkGpqJR42mkjzcjd6qyR1Ctiveir+84/HTtmexouIUn5OFRH5dgyt/gquld31RlHlSYoKho3nZ7D7SnVExov9tp2FGRhU="

# commented out because this call always needed 10+ minutes and time outed for travis
after_success:
  - Rscript -e 'covr::codecov()'
