language: R
sudo: false
cache: packages

r_github_packages:
  - berndbischl/parallelMap
  - jakobbossek/smoof
  - mlr-org/mlr

notifications:
  email:
    recipients:
      - bernd_bischl@gmx.net
      - j.bossek@gmail.com
      - daniel.horn@tu-dortmund.de
      - michellang@gmail.com
      - code@jakob-r.de
    on_success: change
    on_failure: always
